// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDg5UiVKbYxOdDiyIXdF0kOfiDqV-dHM',
    appId: '1:700982728917:web:56178cfd696fb5d6b36a5c',
    messagingSenderId: '700982728917',
    projectId: 'project-z-056',
    authDomain: 'project-z-056.firebaseapp.com',
    storageBucket: 'project-z-056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvaFR__Punbo0-G1m7F3BAxEX7iGSjxaQ',
    appId: '1:700982728917:android:34ac039355c0cf7bb36a5c',
    messagingSenderId: '700982728917',
    projectId: 'project-z-056',
    storageBucket: 'project-z-056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo9IGOSR8bAPu6q5d_iR9xqW4SzVMJAcU',
    appId: '1:700982728917:ios:254cb62dea66caacb36a5c',
    messagingSenderId: '700982728917',
    projectId: 'project-z-056',
    storageBucket: 'project-z-056.firebasestorage.app',
    iosBundleId: 'com.example.project47',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo9IGOSR8bAPu6q5d_iR9xqW4SzVMJAcU',
    appId: '1:700982728917:ios:254cb62dea66caacb36a5c',
    messagingSenderId: '700982728917',
    projectId: 'project-z-056',
    storageBucket: 'project-z-056.firebasestorage.app',
    iosBundleId: 'com.example.project47',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDg5UiVKbYxOdDiyIXdF0kOfiDqV-dHM',
    appId: '1:700982728917:web:53db1464f6bd2fc7b36a5c',
    messagingSenderId: '700982728917',
    projectId: 'project-z-056',
    authDomain: 'project-z-056.firebaseapp.com',
    storageBucket: 'project-z-056.firebasestorage.app',
  );
}
